name = "FastLevenbergMarquardt"
uuid = "7a0df574-e128-4d35-8cbd-3d84502bf7ce"
authors = ["kamesy <ckames@physics.ubc.ca> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
StaticArrays = "1"
julia = "1.6"
